# MongoDB
spring:
  data:
    mongodb:
      database: oauth
      host: ds263307.mlab.com
      port: 63307
      username: ybchoi
      password: dudqja12!

# key
# keytool -genkeypair -alias LHWM5OtDCo -keyalg RSA -dname "CN=Web Server,OU=Unit,O=Organization,L=City,S=State,C=US" -keypass dRuW9QELa5 -keystore server.jks -storepass TYDoDcuEz6
key:
  alias: LHWM5OtDCo
  keypass: dRuW9QELa5
  keystore: server.jks
  storepass: TYDoDcuEz6

# oauth client
oauth:
  admin:
    username: oauthAdmin
    password: password
    clientId: oauth-client
    clientSecret: oauth-secret